name: MLflow CI Training

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Miniconda pakai conda.yaml di MLProject
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          auto-update-conda: true
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml   # <-- path diperbaiki

      # 3. Set MLflow environment
      - name: Set MLflow env
        env:
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/${DAGSHUB_USER}/Workflow-CI-Annisa.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${DAGSHUB_USER}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${DAGSHUB_TOKEN}" >> $GITHUB_ENV

      # 4. Run MLflow Project entry point
      - name: Run MLflow Project
        run: mlflow run MLProject -e main   # <-- jalankan project dari folder MLProject
